#!/usr/bin/env python3
"""Generate zygisk-src/gen/obf_strings.h — build-time XOR string encoding.

Why not constexpr in C++: clang keeps emitting the original string literals
into .rodata (mergeable-string pieces) even when they're only consumed by a
constexpr constructor, so plaintext survived into the .so. Generating the
encoded byte arrays here means no plaintext literal ever enters a translation
unit.

Plaintext lives ONLY in this file (build-time); the generated header and the
.so contain encoded bytes exclusively. Runtime decodes to a stack buffer and
wipes it after use (see obfstr.h).

Encoding must stay in sync with obf::kKey in obfstr.h.
"""

import os

def kkey(i: int) -> int:
    return 0xA5 ^ ((i * 31 + 7) & 0x7F)

# name (C symbol suffix: kObf<name> / kObf<name>Len) -> plaintext
STRINGS = {
    # module paths
    "ExcludeFile":
        "/data/adb/modules/HyperOS3EUXiaoAiPortalMiPay/excluded_packages.txt",
    "DebugFile":
        "/data/adb/modules/HyperOS3EUXiaoAiPortalMiPay/debug",
    "LsplantPath":
        "/data/adb/modules/HyperOS3EUXiaoAiPortalMiPay/zygisk/liblsplant.so",
    # sensitive processes (Google integrity surfaces)
    "Gms":      "com.google.android.gms",
    "Wallet":   "com.google.android.apps.walletnfcrel",
    "Vending":  "com.android.vending",
    # financial processes (TW banks/payments; one per line, trailing '.' =
    # namespace prefix, otherwise exact package) — see main.cpp
    "FinancialList":
        "com.cathaybk.\n"        # 國泰世華 CUBE (mymobibank.android)
        "com.cathaysec.\n"       # 國泰證券
        "com.chb.\n"             # 彰化銀行 (mobile / mobile.pmb)
        "com.chinatrust.\n"      # 中國信託 Home Bank
        "com.esunbank.\n"        # 玉山銀行 / 玉山 Wallet
        "tw.com.taishinbank.\n"  # 台新 (mobile / ccapp / richart)
        "tw.com.megabank.\n"     # 兆豐銀行
        "com.sinopac.\n"         # 永豐 (大戶投等)
        "com.nextbank.\n"        # 將來銀行
        "com.ipass.\n"           # 一卡通 iPASS MONEY
        "tw.gov.post.\n"         # 中華郵政
        "com.jkos.\n"            # 街口支付
        "com.eg.android.AlipayGphone\n"  # 支付寶
        "com.mitake.android.epost\n",    # e動郵局
    # target processes
    "ThemeManager":    "com.android.thememanager",
    "CoreAlive":       "com.miui.voiceassist:voice_trigger",
    "VoiceTrigger":    "com.miui.voicetrigger",
    "VoiceTriggerPfx": "com.miui.voicetrigger:",
    "MiuiHome":        "com.miui.home",
    "MediaEditor":     "com.miui.mediaeditor",
    "SettingsApp":     "com.android.settings",
    # flip target (miui.os.Build)
    "BuildClass": "miui/os/Build",
    "IntlField":  "IS_INTERNATIONAL_BUILD",
    # ThemeManager region-cache hook targets
    "DeviceUtils": "com.android.thememanager.basemodule.utils.DeviceUtils",
    "Ld6Class":    "com.android.thememanager.basemodule.utils.ld6",
    # Settings 憑證頁 hook 目標（app 內部類，見 settingshook.cpp；
    # CredListClass 為 ClassLoader.loadClass 用的點號形式）
    "CredListClass":
        "com.android.settings.applications.credentials.DefaultCombinedPreferenceController",
    "CredListMethod": "getCombinedProviderInfos",
    "CredListSig":    "(Landroid/credentials/CredentialManager;I)Ljava/util/List;",
}

def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "gen", "obf_strings.h")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    lines = [
        "// GENERATED by gen_obf_strings.py — do not edit by hand.",
        "// Plaintext lives only in the generator; see it for the string table.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
    ]
    for name, plain in STRINGS.items():
        raw = plain.encode("utf-8")
        enc = [b ^ kkey(i) for i, b in enumerate(raw)]
        enc.append(0 ^ kkey(len(raw)))  # encoded NUL terminator
        body = ",".join(f"0x{b:02x}" for b in enc)
        # volatile: 防止 -O2 把 decodeStr 常數折疊回明文（constexpr 陣列 +
        # constexpr key 的 XOR 結果編譯期已知，optimizer 會直接把解碼後的
        # 明文當常數池 emit 進 .rodata，XOR 等於白做）。
        lines.append(f"static const volatile unsigned char kObf{name}[] = {{{body}}};")
        lines.append(f"static constexpr size_t kObf{name}Len = {len(raw)};")
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(out_path)

if __name__ == "__main__":
    main()
